### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by sidhshar** [S3Infosoft/s3-loyalty-webapp#1]
Customize README for mvr-loyalty

**Comment by sidhshar** [comment]
At the minimum have the following in your README:
1. Introduction
Explain briefly about the project

2. Installation
How do we get started after we clone the repo

3. Execution
How do we run this? How do we authenticate?

4. Features
Briefly describe top 3 features

5. APIs
Do we expose APIs. Authenticated API?

**Comment by yashpatel7025** [comment]
updated ...

**Comment by sidhshar** [comment]
Cleanup README with parts that are not needed

**Comment by yashpatel7025** [comment]
done
