### ISSUE TITLE
Decouple logic from test1234@gmail.com

### ISSUE THREAD

**Issue by sidhshar** [S3Infosoft/s3-loyalty-webapp#3]
Do not have any variables that are specifically tied to test1234@gmail.com

**Comment by yashpatel7025** [comment]
what is this bug about, I do not understand ,plz elaborate

**Comment by sidhshar** [comment]
Login using any other user and there are no Coupons and Special Deals
![image](https://user-images.githubusercontent.com/20861064/60583207-ffe7ee80-9da7-11e9-94db-43535ad5300e.png)

**Comment by yashpatel7025** [comment]
done
